version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - DEBUG=true
      - LOG_LEVEL=debug
      - MODEL_PROVIDER=${MODEL_PROVIDER:-openai}
      - MODEL_NAME=${MODEL_NAME:-gpt-4}
    volumes:
      - ./app:/app/app
      - ./app/agents:/app/app/agents
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 